version: '3.8'

services:
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_cache:/app/.venv
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - RELOAD=true
      - OTEL_ENABLED=true
      - OTEL_SERVICE_NAME=saas-platform-backend-dev
      # Traces
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=https://otlp.nr-data.net/v1/traces
      - OTEL_EXPORTER_OTLP_TRACES_HEADERS=api-key=${NEW_RELIC_LICENSE_KEY}
      - OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_TRACES_INSECURE=false
      # Metrics
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=https://otlp.nr-data.net/v1/metrics
      - OTEL_EXPORTER_OTLP_METRICS_HEADERS=api-key=${NEW_RELIC_LICENSE_KEY}
      - OTEL_EXPORTER_OTLP_METRICS_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_METRICS_INSECURE=false
      # Logs
      - OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=https://otlp.nr-data.net/v1/logs
      - OTEL_EXPORTER_OTLP_LOGS_HEADERS=api-key=${NEW_RELIC_LICENSE_KEY}
      - OTEL_EXPORTER_OTLP_LOGS_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_LOGS_INSECURE=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - saas-dev-network

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - NEXT_PUBLIC_OTEL_ENABLED=${NEXT_PUBLIC_OTEL_ENABLED}
        - NEXT_PUBLIC_OTEL_SERVICE_NAME=${NEXT_PUBLIC_OTEL_SERVICE_NAME}
        - NEXT_PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=${NEXT_PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT}
        - NEXT_PUBLIC_OTEL_EXPORTER_OTLP_TRACES_HEADERS=${NEXT_PUBLIC_OTEL_EXPORTER_OTLP_TRACES_HEADERS}
        - NEXT_PUBLIC_OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=${NEXT_PUBLIC_OTEL_EXPORTER_OTLP_TRACES_PROTOCOL}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_APP_NAME=SaaS Platform (Dev)
      # Explicitly set Supabase environment variables
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_OTEL_ENABLED=${NEXT_PUBLIC_OTEL_ENABLED}
      - NEXT_PUBLIC_OTEL_SERVICE_NAME=${NEXT_PUBLIC_OTEL_SERVICE_NAME}
      - NEXT_PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=${NEXT_PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT}
      - NEXT_PUBLIC_OTEL_EXPORTER_OTLP_TRACES_HEADERS=${NEXT_PUBLIC_OTEL_EXPORTER_OTLP_TRACES_HEADERS}
      - NEXT_PUBLIC_OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=${NEXT_PUBLIC_OTEL_EXPORTER_OTLP_TRACES_PROTOCOL}
    depends_on:
      backend-dev:
        condition: service_healthy
    networks:
      - saas-dev-network

volumes:
  backend_cache:

networks:
  saas-dev-network:
    driver: bridge