receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://localhost:3000"
            - "http://127.0.0.1:3000"
            - "http://frontend:3000"
            - "http://frontend-dev:3000"
          allowed_headers:
            - "Content-Type"
            - "User-Agent"
            - "Authorization"

exporters:
  otlp/newrelic:
    endpoint: https://otlp.nr-data.net:4317
    headers:
      api-key: ${env:NEW_RELIC_LICENSE_KEY}

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

extensions:
  health_check:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679

service:
  extensions: [health_check, pprof, zpages]
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/newrelic]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/newrelic]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/newrelic]