---
# OpenTelemetry Configuration for Python Auto-Instrumentation

# General configuration
service:
  name: ${OTEL_SERVICE_NAME}
  namespace: saas-platform

# Exporter configuration
exporter:
  otlp:
    # Traces
    traces:
      endpoint: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT}
      headers: ${OTEL_EXPORTER_OTLP_TRACES_HEADERS}
      protocol: http/protobuf
      timeout: 10000
    # Metrics
    metrics:
      endpoint: ${OTEL_EXPORTER_OTLP_METRICS_ENDPOINT}
      headers: ${OTEL_EXPORTER_OTLP_METRICS_HEADERS}
      protocol: http/protobuf
      timeout: 10000
    # Logs
    logs:
      endpoint: ${OTEL_EXPORTER_OTLP_LOGS_ENDPOINT}
      headers: ${OTEL_EXPORTER_OTLP_LOGS_HEADERS}
      protocol: http/protobuf
      timeout: 10000

# Sampler configuration
sampler:
  type: parentbased_always_on
  parent_based:
    local_parent_not_sampled:
      type: always_off
    local_parent_sampled:
      type: always_on
    remote_parent_not_sampled:
      type: always_off
    remote_parent_sampled:
      type: always_on

# Instrumentations
instrumentations:
  - name: "opentelemetry.instrumentation.fastapi"
    enabled: true
  - name: "opentelemetry.instrumentation.requests"
    enabled: true
  - name: "opentelemetry.instrumentation.logging"
    enabled: true
  - name: "opentelemetry.instrumentation.asgi"
    enabled: true

# Resource attributes
resource:
  attributes:
    - key: deployment.environment
      value: ${OTEL_ENVIRONMENT}
    - key: service.version
      value: "1.0.0"